### ISSUE TITLE
Blocking sends

### ISSUE THREAD

**Issue by markusweimer** [Microsoft-CISL/Wake#42]
Sometimes, we need to know that a message has been sent and received by the other side. The case we are looking at right now is the shutdown of an Evaluator: We want to inform the Driver of the shutdown via a last massage and then exit. This is currently not possible because sending is asynchronous and we can't know when a message has left the Evaluator's buffers. Having a blocking send call in Wake would allow us to make sure we get the message out.

**Comment by bgchun** [comment]
This issue will be tracked at https://issues.apache.org/jira/browse/REEF-182.

**Comment by bgchun** [comment]
@markusweimer Can you close this issue?
